version: "3"

volumes:
  log-data:
  driver: local
services:
  fluent-bit:
  image: fluent/fluent-bit
  volumes:
    - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    - ./parsers.conf:/fluent-bit/etc/parsers.conf
    - ./log/:/etc/data