version: "3"

volumes:
  log-data:
services:
  fluent-bit:
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./log/:/etc/data
    networks:
      - opensearch-net
networks:
  opensearch-net:
    name: opensearch-net